url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Sonic Baume" # the name of your site, e.g. ACME Corp.
collections:
  products:
    output: true
  portfolio:
    output: true
picture:
  source: "assets/img/fullsize"
  output: "assets/img/generated"